language: go
go:
  - 1.8
env:
  global:
    - CODECOV_TOKEN: 37544bae-172f-415c-9422-2b619c324f05

install:
  - export SRC=$HOME/gopath/src
  - cd $SRC;ls ./
  - mkdir -p $SRC/github.com/needkane
  - export TRAVIS_BUILD_DIR=$SRC/github.com/needkane/n-exporter
  - cd $TRAVIS_BUILD_DIR
  - go build
  - istanbul cover node_modules/mocha/bin/_mocha
  - cat ./coverage/coverage.json | node_modules/codecov.io/bin/codecov.io.js
